import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

import { ApiErrorBody } from '../../../core/models/api.model';
import { MfaEnrollStart, Session } from '../../../core/models/user.model';
import { Auth } from '../../../core/services/auth';
import { Toast } from '../../../core/services/toast';
import { Users } from '../../../core/services/users';

type MfaStep = 'idle' | 'enrolling' | 'codes';

/** Self-service: personal details, password, MFA and active sessions. */
@Component({
  selector: 'app-profile',
  imports: [ReactiveFormsModule, DatePipe],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './profile.html',
  styleUrl: './profile.scss',
})
export class Profile {
  private readonly users = inject(Users);
  private readonly toast = inject(Toast);
  private readonly fb = inject(FormBuilder);
  private readonly sanitizer = inject(DomSanitizer);
  protected readonly auth = inject(Auth);

  protected readonly saving = signal(false);
  protected readonly changingPassword = signal(false);
  protected readonly profileErrors = signal<Record<string, string>>({});
  protected readonly passwordErrors = signal<Record<string, string>>({});

  protected readonly form = this.fb.nonNullable.group({
    first_name: ['', Validators.required],
    last_name: [''],
    phone: [''],
    designation: [''],
  });

  protected readonly passwordForm = this.fb.nonNullable.group({
    current_password: ['', Validators.required],
    new_password: ['', [Validators.required, Validators.minLength(8)]],
  });

  // -- MFA -----------------------------------------------------------------
  protected readonly mfaStep = signal<MfaStep>('idle');
  protected readonly mfaBusy = signal(false);
  protected readonly mfaError = signal<string | null>(null);
  protected readonly enrollData = signal<MfaEnrollStart | null>(null);
  /** The QR SVG is generated by our own backend from the TOTP secret, never
   * from user input, so trusting it here does not open an XSS hole - see
   * `apps.users.controllers._totp_qr_svg`. */
  protected readonly enrollQrSvg = signal<SafeHtml | null>(null);
  protected readonly recoveryCodes = signal<string[] | null>(null);

  protected readonly enrollForm = this.fb.nonNullable.group({
    code: ['', [Validators.required, Validators.minLength(6)]],
  });
  protected readonly mfaActionForm = this.fb.nonNullable.group({
    current_password: ['', Validators.required],
    code: ['', Validators.required],
  });
  protected showMfaAction = signal<'disable' | 'regenerate' | null>(null);

  // -- Sessions --------------------------------------------------------------
  protected readonly sessions = signal<Session[]>([]);
  protected readonly revokingSessionId = signal<string | null>(null);

  constructor() {
    this.users.profile().subscribe((user) => {
      this.form.patchValue({
        first_name: user.first_name,
        last_name: user.last_name ?? '',
        phone: user.phone ?? '',
        designation: user.designation ?? '',
      });
    });
    this.loadSessions();
  }

  protected save(): void {
    if (this.form.invalid || this.saving()) {
      this.form.markAllAsTouched();
      return;
    }

    this.saving.set(true);
    this.profileErrors.set({});

    this.users.updateProfile(this.form.getRawValue()).subscribe({
      next: (user) => {
        this.saving.set(false);
        this.auth.updateCurrentUser(user);
        this.toast.success('Profile updated.');
      },
      error: (error: ApiErrorBody) => {
        this.saving.set(false);
        this.profileErrors.set(error.details ?? {});
      },
    });
  }

  protected changePassword(): void {
    if (this.passwordForm.invalid || this.changingPassword()) {
      this.passwordForm.markAllAsTouched();
      return;
    }

    this.changingPassword.set(true);
    this.passwordErrors.set({});
    const { current_password, new_password } = this.passwordForm.getRawValue();

    this.auth.changePassword(current_password, new_password).subscribe({
      next: () => {
        this.changingPassword.set(false);
        this.toast.success('Password changed. Please sign in again.');
        // The API revokes every session on a password change.
        setTimeout(() => this.auth.logout(), 1200);
      },
      error: (error: ApiErrorBody) => {
        this.changingPassword.set(false);
        this.passwordErrors.set(error.details ?? { current_password: error.message });
      },
    });
  }

  // -----------------------------------------------------------------
  // MFA
  // -----------------------------------------------------------------
  protected startMfaEnrollment(): void {
    this.mfaBusy.set(true);
    this.mfaError.set(null);
    this.auth.mfaEnrollStart().subscribe({
      next: (data) => {
        this.mfaBusy.set(false);
        this.enrollData.set(data);
        this.enrollQrSvg.set(this.sanitizer.bypassSecurityTrustHtml(data.qr_svg));
        this.enrollForm.reset();
        this.mfaStep.set('enrolling');
      },
      error: (error: ApiErrorBody) => {
        this.mfaBusy.set(false);
        this.mfaError.set(error.message ?? 'Could not start MFA enrollment.');
      },
    });
  }

  protected confirmMfaEnrollment(): void {
    if (this.enrollForm.invalid || this.mfaBusy()) {
      this.enrollForm.markAllAsTouched();
      return;
    }
    this.mfaBusy.set(true);
    this.mfaError.set(null);
    this.auth.mfaEnrollConfirm(this.enrollForm.getRawValue().code.trim()).subscribe({
      next: (result) => {
        this.mfaBusy.set(false);
        this.recoveryCodes.set(result.recovery_codes);
        this.mfaStep.set('codes');
      },
      error: (error: ApiErrorBody) => {
        this.mfaBusy.set(false);
        this.mfaError.set(error.message ?? 'Incorrect code.');
      },
    });
  }

  protected finishMfaEnrollment(): void {
    this.mfaStep.set('idle');
    this.enrollData.set(null);
    this.enrollQrSvg.set(null);
    this.recoveryCodes.set(null);
  }

  protected cancelMfaEnrollment(): void {
    this.finishMfaEnrollment();
  }

  protected openMfaAction(kind: 'disable' | 'regenerate'): void {
    this.mfaActionForm.reset();
    this.mfaError.set(null);
    this.showMfaAction.set(kind);
  }

  protected closeMfaAction(): void {
    this.showMfaAction.set(null);
  }

  protected submitMfaAction(): void {
    if (this.mfaActionForm.invalid || this.mfaBusy()) {
      this.mfaActionForm.markAllAsTouched();
      return;
    }
    const { current_password, code } = this.mfaActionForm.getRawValue();
    const kind = this.showMfaAction();
    this.mfaBusy.set(true);
    this.mfaError.set(null);

    if (kind === 'disable') {
      this.auth.mfaDisable(current_password, code).subscribe({
        next: () => {
          this.mfaBusy.set(false);
          this.showMfaAction.set(null);
          this.toast.success('MFA disabled. You have been signed out on all other devices.');
          this.loadSessions();
        },
        error: (error: ApiErrorBody) => {
          this.mfaBusy.set(false);
          this.mfaError.set(error.message ?? 'Could not disable MFA.');
        },
      });
      return;
    }

    this.auth.mfaRegenerateRecoveryCodes(current_password, code).subscribe({
      next: (result) => {
        this.mfaBusy.set(false);
        this.showMfaAction.set(null);
        this.recoveryCodes.set(result.recovery_codes);
        this.mfaStep.set('codes');
      },
      error: (error: ApiErrorBody) => {
        this.mfaBusy.set(false);
        this.mfaError.set(error.message ?? 'Could not regenerate recovery codes.');
      },
    });
  }

  // -----------------------------------------------------------------
  // Sessions
  // -----------------------------------------------------------------
  private loadSessions(): void {
    this.auth.listSessions().subscribe({
      next: (sessions) => this.sessions.set(sessions),
      error: () => undefined,
    });
  }

  protected revokeSession(session: Session): void {
    this.revokingSessionId.set(session.id);
    this.auth.revokeSession(session.id).subscribe({
      next: () => {
        this.revokingSessionId.set(null);
        this.sessions.update((sessions) => sessions.filter((s) => s.id !== session.id));
        this.toast.success('Session signed out.');
      },
      error: (error: ApiErrorBody) => {
        this.revokingSessionId.set(null);
        this.toast.error(error.message ?? 'Could not sign out that session.');
      },
    });
  }

  protected signOutAllOtherSessions(): void {
    const others = this.sessions().filter((s) => !s.is_current);
    if (!others.length) return;
    others.forEach((session) => this.auth.revokeSession(session.id).subscribe());
    this.toast.success('Signed out of every other device.');
    setTimeout(() => this.loadSessions(), 400);
  }
}
